force-app/main/default/objects/Jet__c/Jet__c.object-meta.xml
<CustomObject>
    <description>A jet is an aircraft for transporting passengers</description>
    <label>Jet</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>JetID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Jet__c/fields/Model_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Name__c</fullName>
    <label>Model Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Jet__c/fields/Next_Inspection__c.field-meta.xml
<CustomField>
    <fullName>Next_Inspection__c</fullName>
    <label>Next Inspection</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Jet__c/fields/Recovery_date__c.field-meta.xml
<CustomField>
    <fullName>Recovery_date__c</fullName>
    <description>A date when this record was undeleted</description>
    <label>Recovery date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Jet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Jet__c/fields/Total_Flown_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Flown_Hours__c</fullName>
    <label>Total Flown Hours</label>
    <summarizedField>Jet_Booking__c.Flight_Duration__c</summarizedField>
    <summaryForeignKey>Jet_Booking__c.Jet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/PJB_JetTriggerHelper.cls
public with sharing class PJB_JetTriggerHelper {
  
    public static void setNextInspectionDate(List<Jet__c> jets){
        
        for(Jet__c jet: jets){
            if(jet.Total_Flown_Hours__c>1000 ){
                Date nextInspection = System.today().AddDays(14);
				Datetime dt = (DateTime)nextInspection;
				String dayOfWeek = dt.format('EEE');
                if(dayOfWeek == 'Sat'){
                    nextInspection=nextInspection.AddDays(2);
                }else if(dayOfWeek == 'Sun'){
                    nextInspection=nextInspection.AddDays(1);
                }
                
                jet.Next_Inspection__c=nextInspection;
            }else if(jet.Status__c=='On Hold'){
                Group g = [SELECT Id FROM Group WHERE Name='Jet Operators'];
                sendNotification(jet,jet.Id,
                 'This is Test Message', new set<String>{Id.valueOf(g.Id)});
            }
            
        } 
    }
    public static void sendNotification(Jet__c jet, String strTargetId, String strTitle, Set<String> setUserIds) {
       
        Messaging.CustomNotification obj = new Messaging.CustomNotification();
        CustomNotificationType notification = [SELECT Id, CustomNotifTypeName, DeveloperName from CustomNotificationType WHERE DeveloperName = 'CustomNotification'];
        obj.setNotificationTypeId(notification.Id);
        obj.setTargetId(strTargetId);
        obj.setTitle(strTitle);
        User user =[SELECT Name FROM User WHERE ID=:jet.LastModifiedById];
        obj.setBody(jet.Model_Name__c+ ' marked on hold by '+ user.Name +'. Please review this jet.');
        obj.send(setUserIds);
    }
    public static void addWhenRecovered(List<Jet__c> jets){
        List<Jet__c> jetsToUpdate = new List<Jet__c>();
        for(Jet__c jet: jets){ 
            jetsToUpdate.add(new Jet__c(Id=jet.Id,Recovery_date__c=DateTime.Now()));
        }
        update jetsToUpdate;
    }
}